spring.application.name=Secure Web Banking Service

# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# DB
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Logging SQL
spring.jpa.show-sql=true

# ---------------- RESILIENCE4J RATE LIMITER ----------------
# LOGIN: max 5 richieste ogni 60s
resilience4j.ratelimiter.instances.loginLimiter.limitForPeriod=5
resilience4j.ratelimiter.instances.loginLimiter.limitRefreshPeriod=60s
resilience4j.ratelimiter.instances.loginLimiter.timeoutDuration=0
# TRANSFER: max 5 bonifici ogni 60s
resilience4j.ratelimiter.instances.transferLimiter.limitForPeriod=5
resilience4j.ratelimiter.instances.transferLimiter.limitRefreshPeriod=60s
resilience4j.ratelimiter.instances.transferLimiter.timeoutDuration=0

#AES
app.crypto.aes-key=0123456789abcdef0123456789abcdef

