spring.application.name=Secure Web Banking Service

# ---------- POSTGRES ----------
spring.datasource.url=jdbc:postgresql://localhost:5432/swbs_db
spring.datasource.username=swbs
spring.datasource.password=swbs_pwd
spring.datasource.driver-class-name=org.postgresql.Driver

# ---------- JPA ----------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ---------------- RESILIENCE4J RATE LIMITER ----------------
# LOGIN: max 5 richieste ogni 60s
resilience4j.ratelimiter.instances.loginLimiter.limitForPeriod=5
resilience4j.ratelimiter.instances.loginLimiter.limitRefreshPeriod=60s
resilience4j.ratelimiter.instances.loginLimiter.timeoutDuration=0
# TRANSFER: max 5 bonifici ogni 60s
resilience4j.ratelimiter.instances.transferLimiter.limitForPeriod=5
resilience4j.ratelimiter.instances.transferLimiter.limitRefreshPeriod=60s
resilience4j.ratelimiter.instances.transferLimiter.timeoutDuration=0

#AES
app.crypto.aes-key=0123456789abcdef0123456789abcdef

