spring.application.name=Secure Web Banking Service

# Database H2 in memoria
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# Abilita console web H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Resilience4j - Rate Limiter
resilience4j.ratelimiter.instances.loginLimiter.limit-for-period=5
resilience4j.ratelimiter.instances.loginLimiter.limit-refresh-period=1m
resilience4j.ratelimiter.instances.loginLimiter.timeout-duration=0
